import 'package:get/get.dart';
import 'package:proyekpertama/Models/poduk_model.dart';


class ListProdukController extends GetxController {

  List<ProdukModel> produkList = [
    ProdukModel(namaProduk: 'Samsung S22 Ultra', hargaProduk: '10 Juta', deskripsiProduk: 'Samsung S22 Ultra adalah smartphone flagship dari Samsung yang dirilis pada tahun 2022. Dilengkapi dengan layar Dynamic AMOLED 2X berukuran 6,8 inci, prosesor Exynos 2200 atau Snapdragon 8 Gen 1, RAM hingga 12GB, dan penyimpanan internal hingga 1TB. Kamera belakangnya memiliki konfigurasi quad-camera dengan sensor utama 108MP, serta baterai berkapasitas 5000mAh yang mendukung pengisian cepat dan nirkabel.', imageProduk: 'assets/samsungs22ultra.jpg', reviewProduk: 'Samsung S22 Ultra menawarkan pengalaman fotografi yang luar biasa dengan kamera berkualitas tinggi dan fitur-fitur canggih. Layar AMOLED yang cerah dan tajam membuat tampilan visual menjadi memukau. Performa yang cepat dan responsif membuat penggunaan sehari-hari menjadi lancar. Namun, harganya yang tinggi mungkin menjadi pertimbangan bagi beberapa pengguna.', ratingProduk: '4.5', spesifikasiProduk: 'Layar: Dynamic AMOLED 2X 6,8 inci\nProsesor: Exynos 2200 / Snapdragon 8 Gen 1\nRAM: Hingga 12GB\nPenyimpanan Internal: Hingga 1TB\nKamera Belakang: Quad-camera (108MP + 12MP + 10MP + 10MP)\nBaterai: 5000mAh dengan pengisian cepat dan nirkabel'),
    ProdukModel(namaProduk: 'Samsung S23 Ultra', hargaProduk: '12 Juta', deskripsiProduk: 'Samsung S23 Ultra adalah smartphone flagship dari Samsung yang dirilis pada tahun 2023. Dilengkapi dengan layar Dynamic AMOLED 2X berukuran 6,8 inci, prosesor Exynos 2300 atau Snapdragon 8 Gen 2, RAM hingga 16GB, dan penyimpanan internal hingga 1TB. Kamera belakangnya memiliki konfigurasi quad-camera dengan sensor utama 200MP, serta baterai berkapasitas 5000mAh yang mendukung pengisian cepat dan nirkabel.', imageProduk: 'assets/samsungs23ultra.jpg', reviewProduk: 'Samsung S23 Ultra menawarkan performa yang luar biasa dengan prosesor terbaru dan kamera berkualitas tinggi. Layar AMOLED yang cerah dan tajam membuat tampilan visual menjadi memukau. Namun, harganya yang tinggi mungkin menjadi pertimbangan bagi beberapa pengguna.', ratingProduk: '4.7', spesifikasiProduk: 'Layar: Dynamic AMOLED 2X 6,8 inci\nProsesor: Exynos 2300 / Snapdragon 8 Gen 2\nRAM: Hingga 16GB\nPenyimpanan Internal: Hingga 1TB\nKamera Belakang: Quad-camera (200MP + 12MP + 10MP + 10MP)\nBaterai: 5000mAh dengan pengisian cepat dan nirkabel'),
    ProdukModel(namaProduk: 'iPhone 14 Pro', hargaProduk: '15 Juta', deskripsiProduk: 'iPhone 14 Pro adalah smartphone terbaru dari Apple yang dirilis pada tahun 2022. Dilengkapi dengan layar Super Retina XDR berukuran 6,1 inci, prosesor A16 Bionic, RAM hingga 6GB, dan penyimpanan internal hingga 1TB. Kamera belakangnya memiliki konfigurasi triple-camera dengan sensor utama 12MP, serta baterai berkapasitas hingga beberapa jam yang mendukung pengisian cepat.', imageProduk: 'assets/iphone14pro.jpg', reviewProduk: 'iPhone 14 Pro menawarkan pengalaman penggunaan yang luar biasa dengan performa yang cepat dan kamera berkualitas tinggi. Layar Super Retina XDR yang cerah dan tajam membuat tampilan visual menjadi memukau. Namun, harganya yang tinggi mungkin menjadi pertimbangan bagi beberapa pengguna.', ratingProduk: '4.6', spesifikasiProduk: 'Layar: Super Retina XDR 6,1 inci\nProsesor: A16 Bionic\nRAM: Hingga 6GB\nPenyimpanan Internal: Hingga 1TB\nKamera Belakang: Triple-camera (12MP + 12MP + 12MP)\nBaterai: Hingga beberapa jam dengan pengisian cepat'),
    ProdukModel(namaProduk: 'iPhone 15 Pro', hargaProduk: '20 Juta', deskripsiProduk: 'iPhone 15 Pro adalah smartphone terbaru dari Apple yang dirilis pada tahun 2023. Dilengkapi dengan layar Super Retina XDR berukuran 6,1 inci, prosesor A17 Bionic, RAM hingga 8GB, dan penyimpanan internal hingga 1TB. Kamera belakangnya memiliki konfigurasi triple-camera dengan sensor utama 48MP, serta baterai berkapasitas hingga beberapa jam yang mendukung pengisian cepat.', imageProduk: 'assets/iphone15pro.jpg', reviewProduk: 'iPhone 15 Pro menawarkan performa yang luar biasa dengan prosesor terbaru dan kamera berkualitas tinggi. Layar Super Retina XDR yang cerah dan tajam membuat tampilan visual menjadi memukau. Namun, harganya yang tinggi mungkin menjadi pertimbangan bagi beberapa pengguna.', ratingProduk: '4.8', spesifikasiProduk: 'Layar: Super Retina XDR 6,1 inci\nProsesor: A17 Bionic\nRAM: Hingga 8GB\nPenyimpanan Internal: Hingga 1TB\nKamera Belakang: Triple-camera (48MP + 12MP + 12MP)\nBaterai: Hingga beberapa jam dengan pengisian cepat'),
    ProdukModel(namaProduk: 'Xiaomi 13 Pro',hargaProduk: '14 Juta',deskripsiProduk: 'Xiaomi 13 Pro adalah HP flagship dengan kamera hasil kolaborasi Leica. Dibekali layar LTPO AMOLED 6,73 inci, chipset Snapdragon 8 Gen 2, RAM 12GB, serta pengisian daya super cepat HyperCharge 120W.',imageProduk: 'assets/xiaomy13pro.jpg',reviewProduk: 'Kualitas foto Leica sangat memuaskan dengan warna khas yang estetik. Performa kencang untuk game berat dan pengisian daya sangat cepat. Desain bodinya terasa kokoh dan premium.',ratingProduk: '4.7',spesifikasiProduk: 'Layar: LTPO AMOLED 6,73 inci 120Hz\nProsesor: Snapdragon 8 Gen 2\nRAM: 12GB\nPenyimpanan Internal: 256GB / 512GB\nKamera Belakang: Triple-camera Leica (50MP + 50MP + 50MP)\nBaterai: 4820mAh dengan 120W HyperCharge',),
    ];
}